
// generated by gocc; DO NOT EDIT.

package lexer

import (
	
	// "fmt"
	// "github.com/sjhitchner/go-pred/util"
	
	"io/ioutil"
	"unicode/utf8"
	"github.com/sjhitchner/go-pred/token"
)

const(
	NoState = -1
	NumStates = 77
	NumSymbols = 86
)

type Lexer struct {
	src             []byte
	pos             int
	line            int
	column          int
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:    src,
		pos:    0,
		line:   1,
		column: 1,
	}
	return lexer
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := ioutil.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	return NewLexer(src), nil
}

func (this *Lexer) Scan() (tok *token.Token) {
	
	// fmt.Printf("Lexer.Scan() pos=%d\n", this.pos)
	
	tok = new(token.Token)
	if this.pos >= len(this.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = this.pos, this.line, this.column
		return
	}
	start, end := this.pos, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
	
		// fmt.Printf("\tpos=%d, line=%d, col=%d, state=%d\n", this.pos, this.line, this.column, state)
	
		if this.pos >= len(this.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(this.src[this.pos:])
			this.pos += size
		}
		switch rune1 {
		case '\n':
			this.line++
			this.column = 1
		case '\r':
			this.column = 1
		case '\t':
			this.column += 4
		default:
			this.column++
		}

	
		// Production start
		if rune1 != -1 {
			state = TransTab[state](rune1)
		} else {
			state = -1
		}
		// Production end

		// Debug start
		// nextState := -1
		// if rune1 != -1 {
		// 	nextState = TransTab[state](rune1)
		// }
		// fmt.Printf("\tS%d, : tok=%s, rune == %s(%x), next state == %d\n", state, token.TokMap.Id(tok.Type), util.RuneToString(rune1), rune1, nextState)
		// fmt.Printf("\t\tpos=%d, size=%d, start=%d, end=%d\n", this.pos, size, start, end)
		// if nextState != -1 {
		// 	fmt.Printf("\t\taction:%s\n", ActTab[nextState].String())
		// }
		// state = nextState
		// Debug end
	

		if state != -1 {
			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				// fmt.Printf("\t Accept(%s), %s(%d)\n", string(act), token.TokMap.Id(tok), tok)
				end = this.pos
			case ActTab[state].Ignore != "":
				// fmt.Printf("\t Ignore(%s)\n", string(act))
				start = this.pos
				state = 0
				if start >= len(this.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = this.pos
			}
		}
	}
	if end > start {
		this.pos = end
		tok.Lit = this.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset = start
	tok.Pos.Column = this.column
	tok.Pos.Line = this.line
	return
}

func (this *Lexer) Reset() {
	this.pos = 0
}

/*
Lexer symbols:
0: '.'
1: '_'
2: '.'
3: '"'
4: '"'
5: '''
6: '''
7: 'a'
8: 'n'
9: 'd'
10: 'o'
11: 'r'
12: 'n'
13: 'o'
14: 't'
15: '>'
16: '>'
17: '='
18: '<'
19: '<'
20: '='
21: '='
22: '='
23: '='
24: '!'
25: '='
26: 'i'
27: 's'
28: ' '
29: 'n'
30: 'o'
31: 't'
32: 'i'
33: 's'
34: 'c'
35: 'o'
36: 'n'
37: 't'
38: 'a'
39: 'i'
40: 'n'
41: 's'
42: 'm'
43: 'a'
44: 't'
45: 'c'
46: 'h'
47: 'e'
48: 's'
49: 't'
50: 'r'
51: 'u'
52: 'e'
53: 'f'
54: 'a'
55: 'l'
56: 's'
57: 'e'
58: 'u'
59: 'n'
60: 'd'
61: 'e'
62: 'f'
63: 'i'
64: 'n'
65: 'e'
66: 'd'
67: 'n'
68: 'u'
69: 'l'
70: 'l'
71: 'e'
72: 'm'
73: 'p'
74: 't'
75: 'y'
76: '('
77: ')'
78: ' '
79: '\t'
80: '\n'
81: '\r'
82: '0'-'9'
83: 'a'-'z'
84: 'A'-'Z'
85: .

*/
