
// generated by gocc; DO NOT EDIT.

package parser

type(
	actionTable [numStates]actionRow
	actionRow struct {
		canRecover bool
		actions [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(25),		/* $, reduce: Factor */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			shift(2),		/* not */
			reduce(25),		/* >, reduce: Factor */
			reduce(25),		/* >=, reduce: Factor */
			reduce(25),		/* <, reduce: Factor */
			reduce(25),		/* <=, reduce: Factor */
			reduce(25),		/* =, reduce: Factor */
			reduce(25),		/* ==, reduce: Factor */
			reduce(25),		/* !=, reduce: Factor */
			reduce(25),		/* is not, reduce: Factor */
			reduce(25),		/* is, reduce: Factor */
			reduce(25),		/* contains, reduce: Factor */
			reduce(25),		/* matches, reduce: Factor */
			shift(5),		/* int_lit */
			shift(6),		/* string_lit */
			shift(7),		/* float_lit */
			shift(8),		/* variable */
			shift(9),		/* true */
			shift(10),		/* false */
			shift(11),		/* undefined */
			shift(12),		/* null */
			nil,		/* empty */
			shift(13),		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S1
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			accept(true),		/* $ */
			shift(14),		/* and */
			shift(15),		/* or */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S2
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(25),		/* $, reduce: Factor */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			shift(2),		/* not */
			reduce(25),		/* >, reduce: Factor */
			reduce(25),		/* >=, reduce: Factor */
			reduce(25),		/* <, reduce: Factor */
			reduce(25),		/* <=, reduce: Factor */
			reduce(25),		/* =, reduce: Factor */
			reduce(25),		/* ==, reduce: Factor */
			reduce(25),		/* !=, reduce: Factor */
			reduce(25),		/* is not, reduce: Factor */
			reduce(25),		/* is, reduce: Factor */
			reduce(25),		/* contains, reduce: Factor */
			reduce(25),		/* matches, reduce: Factor */
			shift(5),		/* int_lit */
			shift(6),		/* string_lit */
			shift(7),		/* float_lit */
			shift(8),		/* variable */
			shift(9),		/* true */
			shift(10),		/* false */
			shift(11),		/* undefined */
			shift(12),		/* null */
			nil,		/* empty */
			shift(13),		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S3
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(4),		/* $, reduce: Expression */
			reduce(4),		/* and, reduce: Expression */
			reduce(4),		/* or, reduce: Expression */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S4
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(16),		/* $, reduce: Term */
			reduce(16),		/* and, reduce: Term */
			reduce(16),		/* or, reduce: Term */
			nil,		/* not */
			shift(17),		/* > */
			shift(18),		/* >= */
			shift(19),		/* < */
			shift(20),		/* <= */
			shift(21),		/* = */
			shift(22),		/* == */
			shift(23),		/* != */
			shift(24),		/* is not */
			shift(25),		/* is */
			shift(26),		/* contains */
			shift(27),		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S5
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(17),		/* $, reduce: Factor */
			reduce(17),		/* and, reduce: Factor */
			reduce(17),		/* or, reduce: Factor */
			nil,		/* not */
			reduce(17),		/* >, reduce: Factor */
			reduce(17),		/* >=, reduce: Factor */
			reduce(17),		/* <, reduce: Factor */
			reduce(17),		/* <=, reduce: Factor */
			reduce(17),		/* =, reduce: Factor */
			reduce(17),		/* ==, reduce: Factor */
			reduce(17),		/* !=, reduce: Factor */
			reduce(17),		/* is not, reduce: Factor */
			reduce(17),		/* is, reduce: Factor */
			reduce(17),		/* contains, reduce: Factor */
			reduce(17),		/* matches, reduce: Factor */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S6
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(18),		/* $, reduce: Factor */
			reduce(18),		/* and, reduce: Factor */
			reduce(18),		/* or, reduce: Factor */
			nil,		/* not */
			reduce(18),		/* >, reduce: Factor */
			reduce(18),		/* >=, reduce: Factor */
			reduce(18),		/* <, reduce: Factor */
			reduce(18),		/* <=, reduce: Factor */
			reduce(18),		/* =, reduce: Factor */
			reduce(18),		/* ==, reduce: Factor */
			reduce(18),		/* !=, reduce: Factor */
			reduce(18),		/* is not, reduce: Factor */
			reduce(18),		/* is, reduce: Factor */
			reduce(18),		/* contains, reduce: Factor */
			reduce(18),		/* matches, reduce: Factor */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S7
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(19),		/* $, reduce: Factor */
			reduce(19),		/* and, reduce: Factor */
			reduce(19),		/* or, reduce: Factor */
			nil,		/* not */
			reduce(19),		/* >, reduce: Factor */
			reduce(19),		/* >=, reduce: Factor */
			reduce(19),		/* <, reduce: Factor */
			reduce(19),		/* <=, reduce: Factor */
			reduce(19),		/* =, reduce: Factor */
			reduce(19),		/* ==, reduce: Factor */
			reduce(19),		/* !=, reduce: Factor */
			reduce(19),		/* is not, reduce: Factor */
			reduce(19),		/* is, reduce: Factor */
			reduce(19),		/* contains, reduce: Factor */
			reduce(19),		/* matches, reduce: Factor */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S8
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(20),		/* $, reduce: Factor */
			reduce(20),		/* and, reduce: Factor */
			reduce(20),		/* or, reduce: Factor */
			nil,		/* not */
			reduce(20),		/* >, reduce: Factor */
			reduce(20),		/* >=, reduce: Factor */
			reduce(20),		/* <, reduce: Factor */
			reduce(20),		/* <=, reduce: Factor */
			reduce(20),		/* =, reduce: Factor */
			reduce(20),		/* ==, reduce: Factor */
			reduce(20),		/* !=, reduce: Factor */
			reduce(20),		/* is not, reduce: Factor */
			reduce(20),		/* is, reduce: Factor */
			reduce(20),		/* contains, reduce: Factor */
			reduce(20),		/* matches, reduce: Factor */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S9
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(21),		/* $, reduce: Factor */
			reduce(21),		/* and, reduce: Factor */
			reduce(21),		/* or, reduce: Factor */
			nil,		/* not */
			reduce(21),		/* >, reduce: Factor */
			reduce(21),		/* >=, reduce: Factor */
			reduce(21),		/* <, reduce: Factor */
			reduce(21),		/* <=, reduce: Factor */
			reduce(21),		/* =, reduce: Factor */
			reduce(21),		/* ==, reduce: Factor */
			reduce(21),		/* !=, reduce: Factor */
			reduce(21),		/* is not, reduce: Factor */
			reduce(21),		/* is, reduce: Factor */
			reduce(21),		/* contains, reduce: Factor */
			reduce(21),		/* matches, reduce: Factor */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S10
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(22),		/* $, reduce: Factor */
			reduce(22),		/* and, reduce: Factor */
			reduce(22),		/* or, reduce: Factor */
			nil,		/* not */
			reduce(22),		/* >, reduce: Factor */
			reduce(22),		/* >=, reduce: Factor */
			reduce(22),		/* <, reduce: Factor */
			reduce(22),		/* <=, reduce: Factor */
			reduce(22),		/* =, reduce: Factor */
			reduce(22),		/* ==, reduce: Factor */
			reduce(22),		/* !=, reduce: Factor */
			reduce(22),		/* is not, reduce: Factor */
			reduce(22),		/* is, reduce: Factor */
			reduce(22),		/* contains, reduce: Factor */
			reduce(22),		/* matches, reduce: Factor */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S11
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(23),		/* $, reduce: Factor */
			reduce(23),		/* and, reduce: Factor */
			reduce(23),		/* or, reduce: Factor */
			nil,		/* not */
			reduce(23),		/* >, reduce: Factor */
			reduce(23),		/* >=, reduce: Factor */
			reduce(23),		/* <, reduce: Factor */
			reduce(23),		/* <=, reduce: Factor */
			reduce(23),		/* =, reduce: Factor */
			reduce(23),		/* ==, reduce: Factor */
			reduce(23),		/* !=, reduce: Factor */
			reduce(23),		/* is not, reduce: Factor */
			reduce(23),		/* is, reduce: Factor */
			reduce(23),		/* contains, reduce: Factor */
			reduce(23),		/* matches, reduce: Factor */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S12
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(24),		/* $, reduce: Factor */
			reduce(24),		/* and, reduce: Factor */
			reduce(24),		/* or, reduce: Factor */
			nil,		/* not */
			reduce(24),		/* >, reduce: Factor */
			reduce(24),		/* >=, reduce: Factor */
			reduce(24),		/* <, reduce: Factor */
			reduce(24),		/* <=, reduce: Factor */
			reduce(24),		/* =, reduce: Factor */
			reduce(24),		/* ==, reduce: Factor */
			reduce(24),		/* !=, reduce: Factor */
			reduce(24),		/* is not, reduce: Factor */
			reduce(24),		/* is, reduce: Factor */
			reduce(24),		/* contains, reduce: Factor */
			reduce(24),		/* matches, reduce: Factor */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S13
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			shift(29),		/* not */
			reduce(25),		/* >, reduce: Factor */
			reduce(25),		/* >=, reduce: Factor */
			reduce(25),		/* <, reduce: Factor */
			reduce(25),		/* <=, reduce: Factor */
			reduce(25),		/* =, reduce: Factor */
			reduce(25),		/* ==, reduce: Factor */
			reduce(25),		/* !=, reduce: Factor */
			reduce(25),		/* is not, reduce: Factor */
			reduce(25),		/* is, reduce: Factor */
			reduce(25),		/* contains, reduce: Factor */
			reduce(25),		/* matches, reduce: Factor */
			shift(32),		/* int_lit */
			shift(33),		/* string_lit */
			shift(34),		/* float_lit */
			shift(35),		/* variable */
			shift(36),		/* true */
			shift(37),		/* false */
			shift(38),		/* undefined */
			shift(39),		/* null */
			nil,		/* empty */
			shift(40),		/* ( */
			reduce(25),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S14
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(25),		/* $, reduce: Factor */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			shift(2),		/* not */
			reduce(25),		/* >, reduce: Factor */
			reduce(25),		/* >=, reduce: Factor */
			reduce(25),		/* <, reduce: Factor */
			reduce(25),		/* <=, reduce: Factor */
			reduce(25),		/* =, reduce: Factor */
			reduce(25),		/* ==, reduce: Factor */
			reduce(25),		/* !=, reduce: Factor */
			reduce(25),		/* is not, reduce: Factor */
			reduce(25),		/* is, reduce: Factor */
			reduce(25),		/* contains, reduce: Factor */
			reduce(25),		/* matches, reduce: Factor */
			shift(5),		/* int_lit */
			shift(6),		/* string_lit */
			shift(7),		/* float_lit */
			shift(8),		/* variable */
			shift(9),		/* true */
			shift(10),		/* false */
			shift(11),		/* undefined */
			shift(12),		/* null */
			nil,		/* empty */
			shift(13),		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S15
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(25),		/* $, reduce: Factor */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			shift(2),		/* not */
			reduce(25),		/* >, reduce: Factor */
			reduce(25),		/* >=, reduce: Factor */
			reduce(25),		/* <, reduce: Factor */
			reduce(25),		/* <=, reduce: Factor */
			reduce(25),		/* =, reduce: Factor */
			reduce(25),		/* ==, reduce: Factor */
			reduce(25),		/* !=, reduce: Factor */
			reduce(25),		/* is not, reduce: Factor */
			reduce(25),		/* is, reduce: Factor */
			reduce(25),		/* contains, reduce: Factor */
			reduce(25),		/* matches, reduce: Factor */
			shift(5),		/* int_lit */
			shift(6),		/* string_lit */
			shift(7),		/* float_lit */
			shift(8),		/* variable */
			shift(9),		/* true */
			shift(10),		/* false */
			shift(11),		/* undefined */
			shift(12),		/* null */
			nil,		/* empty */
			shift(13),		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S16
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(3),		/* $, reduce: Expression */
			shift(14),		/* and */
			shift(15),		/* or */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S17
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(25),		/* $, reduce: Factor */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(44),		/* int_lit */
			shift(45),		/* string_lit */
			shift(46),		/* float_lit */
			shift(47),		/* variable */
			shift(48),		/* true */
			shift(49),		/* false */
			shift(50),		/* undefined */
			shift(51),		/* null */
			nil,		/* empty */
			shift(52),		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S18
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(25),		/* $, reduce: Factor */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(44),		/* int_lit */
			shift(45),		/* string_lit */
			shift(46),		/* float_lit */
			shift(47),		/* variable */
			shift(48),		/* true */
			shift(49),		/* false */
			shift(50),		/* undefined */
			shift(51),		/* null */
			nil,		/* empty */
			shift(52),		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S19
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(25),		/* $, reduce: Factor */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(44),		/* int_lit */
			shift(45),		/* string_lit */
			shift(46),		/* float_lit */
			shift(47),		/* variable */
			shift(48),		/* true */
			shift(49),		/* false */
			shift(50),		/* undefined */
			shift(51),		/* null */
			nil,		/* empty */
			shift(52),		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S20
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(25),		/* $, reduce: Factor */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(44),		/* int_lit */
			shift(45),		/* string_lit */
			shift(46),		/* float_lit */
			shift(47),		/* variable */
			shift(48),		/* true */
			shift(49),		/* false */
			shift(50),		/* undefined */
			shift(51),		/* null */
			nil,		/* empty */
			shift(52),		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S21
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(25),		/* $, reduce: Factor */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(44),		/* int_lit */
			shift(45),		/* string_lit */
			shift(46),		/* float_lit */
			shift(47),		/* variable */
			shift(48),		/* true */
			shift(49),		/* false */
			shift(50),		/* undefined */
			shift(51),		/* null */
			nil,		/* empty */
			shift(52),		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S22
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(25),		/* $, reduce: Factor */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(44),		/* int_lit */
			shift(45),		/* string_lit */
			shift(46),		/* float_lit */
			shift(47),		/* variable */
			shift(48),		/* true */
			shift(49),		/* false */
			shift(50),		/* undefined */
			shift(51),		/* null */
			nil,		/* empty */
			shift(52),		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S23
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(25),		/* $, reduce: Factor */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(44),		/* int_lit */
			shift(45),		/* string_lit */
			shift(46),		/* float_lit */
			shift(47),		/* variable */
			shift(48),		/* true */
			shift(49),		/* false */
			shift(50),		/* undefined */
			shift(51),		/* null */
			nil,		/* empty */
			shift(52),		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S24
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(25),		/* $, reduce: Factor */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(44),		/* int_lit */
			shift(45),		/* string_lit */
			shift(46),		/* float_lit */
			shift(47),		/* variable */
			shift(48),		/* true */
			shift(49),		/* false */
			shift(50),		/* undefined */
			shift(51),		/* null */
			nil,		/* empty */
			shift(52),		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S25
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(25),		/* $, reduce: Factor */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(44),		/* int_lit */
			shift(45),		/* string_lit */
			shift(46),		/* float_lit */
			shift(47),		/* variable */
			shift(48),		/* true */
			shift(49),		/* false */
			shift(50),		/* undefined */
			shift(51),		/* null */
			nil,		/* empty */
			shift(52),		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S26
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(25),		/* $, reduce: Factor */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(44),		/* int_lit */
			shift(45),		/* string_lit */
			shift(46),		/* float_lit */
			shift(47),		/* variable */
			shift(48),		/* true */
			shift(49),		/* false */
			shift(50),		/* undefined */
			shift(51),		/* null */
			nil,		/* empty */
			shift(52),		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S27
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(25),		/* $, reduce: Factor */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(44),		/* int_lit */
			shift(45),		/* string_lit */
			shift(46),		/* float_lit */
			shift(47),		/* variable */
			shift(48),		/* true */
			shift(49),		/* false */
			shift(50),		/* undefined */
			shift(51),		/* null */
			nil,		/* empty */
			shift(52),		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S28
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			shift(63),		/* and */
			shift(64),		/* or */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			shift(65),		/* ) */
			
		},

	},
	actionRow{ // S29
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			shift(29),		/* not */
			reduce(25),		/* >, reduce: Factor */
			reduce(25),		/* >=, reduce: Factor */
			reduce(25),		/* <, reduce: Factor */
			reduce(25),		/* <=, reduce: Factor */
			reduce(25),		/* =, reduce: Factor */
			reduce(25),		/* ==, reduce: Factor */
			reduce(25),		/* !=, reduce: Factor */
			reduce(25),		/* is not, reduce: Factor */
			reduce(25),		/* is, reduce: Factor */
			reduce(25),		/* contains, reduce: Factor */
			reduce(25),		/* matches, reduce: Factor */
			shift(32),		/* int_lit */
			shift(33),		/* string_lit */
			shift(34),		/* float_lit */
			shift(35),		/* variable */
			shift(36),		/* true */
			shift(37),		/* false */
			shift(38),		/* undefined */
			shift(39),		/* null */
			nil,		/* empty */
			shift(40),		/* ( */
			reduce(25),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S30
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(4),		/* and, reduce: Expression */
			reduce(4),		/* or, reduce: Expression */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(4),		/* ), reduce: Expression */
			
		},

	},
	actionRow{ // S31
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(16),		/* and, reduce: Term */
			reduce(16),		/* or, reduce: Term */
			nil,		/* not */
			shift(67),		/* > */
			shift(68),		/* >= */
			shift(69),		/* < */
			shift(70),		/* <= */
			shift(71),		/* = */
			shift(72),		/* == */
			shift(73),		/* != */
			shift(74),		/* is not */
			shift(75),		/* is */
			shift(76),		/* contains */
			shift(77),		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(16),		/* ), reduce: Term */
			
		},

	},
	actionRow{ // S32
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(17),		/* and, reduce: Factor */
			reduce(17),		/* or, reduce: Factor */
			nil,		/* not */
			reduce(17),		/* >, reduce: Factor */
			reduce(17),		/* >=, reduce: Factor */
			reduce(17),		/* <, reduce: Factor */
			reduce(17),		/* <=, reduce: Factor */
			reduce(17),		/* =, reduce: Factor */
			reduce(17),		/* ==, reduce: Factor */
			reduce(17),		/* !=, reduce: Factor */
			reduce(17),		/* is not, reduce: Factor */
			reduce(17),		/* is, reduce: Factor */
			reduce(17),		/* contains, reduce: Factor */
			reduce(17),		/* matches, reduce: Factor */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(17),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S33
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(18),		/* and, reduce: Factor */
			reduce(18),		/* or, reduce: Factor */
			nil,		/* not */
			reduce(18),		/* >, reduce: Factor */
			reduce(18),		/* >=, reduce: Factor */
			reduce(18),		/* <, reduce: Factor */
			reduce(18),		/* <=, reduce: Factor */
			reduce(18),		/* =, reduce: Factor */
			reduce(18),		/* ==, reduce: Factor */
			reduce(18),		/* !=, reduce: Factor */
			reduce(18),		/* is not, reduce: Factor */
			reduce(18),		/* is, reduce: Factor */
			reduce(18),		/* contains, reduce: Factor */
			reduce(18),		/* matches, reduce: Factor */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(18),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S34
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(19),		/* and, reduce: Factor */
			reduce(19),		/* or, reduce: Factor */
			nil,		/* not */
			reduce(19),		/* >, reduce: Factor */
			reduce(19),		/* >=, reduce: Factor */
			reduce(19),		/* <, reduce: Factor */
			reduce(19),		/* <=, reduce: Factor */
			reduce(19),		/* =, reduce: Factor */
			reduce(19),		/* ==, reduce: Factor */
			reduce(19),		/* !=, reduce: Factor */
			reduce(19),		/* is not, reduce: Factor */
			reduce(19),		/* is, reduce: Factor */
			reduce(19),		/* contains, reduce: Factor */
			reduce(19),		/* matches, reduce: Factor */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(19),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S35
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(20),		/* and, reduce: Factor */
			reduce(20),		/* or, reduce: Factor */
			nil,		/* not */
			reduce(20),		/* >, reduce: Factor */
			reduce(20),		/* >=, reduce: Factor */
			reduce(20),		/* <, reduce: Factor */
			reduce(20),		/* <=, reduce: Factor */
			reduce(20),		/* =, reduce: Factor */
			reduce(20),		/* ==, reduce: Factor */
			reduce(20),		/* !=, reduce: Factor */
			reduce(20),		/* is not, reduce: Factor */
			reduce(20),		/* is, reduce: Factor */
			reduce(20),		/* contains, reduce: Factor */
			reduce(20),		/* matches, reduce: Factor */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(20),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S36
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(21),		/* and, reduce: Factor */
			reduce(21),		/* or, reduce: Factor */
			nil,		/* not */
			reduce(21),		/* >, reduce: Factor */
			reduce(21),		/* >=, reduce: Factor */
			reduce(21),		/* <, reduce: Factor */
			reduce(21),		/* <=, reduce: Factor */
			reduce(21),		/* =, reduce: Factor */
			reduce(21),		/* ==, reduce: Factor */
			reduce(21),		/* !=, reduce: Factor */
			reduce(21),		/* is not, reduce: Factor */
			reduce(21),		/* is, reduce: Factor */
			reduce(21),		/* contains, reduce: Factor */
			reduce(21),		/* matches, reduce: Factor */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(21),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S37
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(22),		/* and, reduce: Factor */
			reduce(22),		/* or, reduce: Factor */
			nil,		/* not */
			reduce(22),		/* >, reduce: Factor */
			reduce(22),		/* >=, reduce: Factor */
			reduce(22),		/* <, reduce: Factor */
			reduce(22),		/* <=, reduce: Factor */
			reduce(22),		/* =, reduce: Factor */
			reduce(22),		/* ==, reduce: Factor */
			reduce(22),		/* !=, reduce: Factor */
			reduce(22),		/* is not, reduce: Factor */
			reduce(22),		/* is, reduce: Factor */
			reduce(22),		/* contains, reduce: Factor */
			reduce(22),		/* matches, reduce: Factor */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(22),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S38
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(23),		/* and, reduce: Factor */
			reduce(23),		/* or, reduce: Factor */
			nil,		/* not */
			reduce(23),		/* >, reduce: Factor */
			reduce(23),		/* >=, reduce: Factor */
			reduce(23),		/* <, reduce: Factor */
			reduce(23),		/* <=, reduce: Factor */
			reduce(23),		/* =, reduce: Factor */
			reduce(23),		/* ==, reduce: Factor */
			reduce(23),		/* !=, reduce: Factor */
			reduce(23),		/* is not, reduce: Factor */
			reduce(23),		/* is, reduce: Factor */
			reduce(23),		/* contains, reduce: Factor */
			reduce(23),		/* matches, reduce: Factor */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(23),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S39
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(24),		/* and, reduce: Factor */
			reduce(24),		/* or, reduce: Factor */
			nil,		/* not */
			reduce(24),		/* >, reduce: Factor */
			reduce(24),		/* >=, reduce: Factor */
			reduce(24),		/* <, reduce: Factor */
			reduce(24),		/* <=, reduce: Factor */
			reduce(24),		/* =, reduce: Factor */
			reduce(24),		/* ==, reduce: Factor */
			reduce(24),		/* !=, reduce: Factor */
			reduce(24),		/* is not, reduce: Factor */
			reduce(24),		/* is, reduce: Factor */
			reduce(24),		/* contains, reduce: Factor */
			reduce(24),		/* matches, reduce: Factor */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(24),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S40
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			shift(29),		/* not */
			reduce(25),		/* >, reduce: Factor */
			reduce(25),		/* >=, reduce: Factor */
			reduce(25),		/* <, reduce: Factor */
			reduce(25),		/* <=, reduce: Factor */
			reduce(25),		/* =, reduce: Factor */
			reduce(25),		/* ==, reduce: Factor */
			reduce(25),		/* !=, reduce: Factor */
			reduce(25),		/* is not, reduce: Factor */
			reduce(25),		/* is, reduce: Factor */
			reduce(25),		/* contains, reduce: Factor */
			reduce(25),		/* matches, reduce: Factor */
			shift(32),		/* int_lit */
			shift(33),		/* string_lit */
			shift(34),		/* float_lit */
			shift(35),		/* variable */
			shift(36),		/* true */
			shift(37),		/* false */
			shift(38),		/* undefined */
			shift(39),		/* null */
			nil,		/* empty */
			shift(40),		/* ( */
			reduce(25),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S41
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(1),		/* $, reduce: Expression */
			shift(14),		/* and */
			shift(15),		/* or */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S42
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(2),		/* $, reduce: Expression */
			shift(14),		/* and */
			shift(15),		/* or */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S43
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(5),		/* $, reduce: Term */
			reduce(5),		/* and, reduce: Term */
			reduce(5),		/* or, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S44
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(17),		/* $, reduce: Factor */
			reduce(17),		/* and, reduce: Factor */
			reduce(17),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S45
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(18),		/* $, reduce: Factor */
			reduce(18),		/* and, reduce: Factor */
			reduce(18),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S46
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(19),		/* $, reduce: Factor */
			reduce(19),		/* and, reduce: Factor */
			reduce(19),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S47
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(20),		/* $, reduce: Factor */
			reduce(20),		/* and, reduce: Factor */
			reduce(20),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S48
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(21),		/* $, reduce: Factor */
			reduce(21),		/* and, reduce: Factor */
			reduce(21),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S49
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(22),		/* $, reduce: Factor */
			reduce(22),		/* and, reduce: Factor */
			reduce(22),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S50
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(23),		/* $, reduce: Factor */
			reduce(23),		/* and, reduce: Factor */
			reduce(23),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S51
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(24),		/* $, reduce: Factor */
			reduce(24),		/* and, reduce: Factor */
			reduce(24),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S52
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			shift(29),		/* not */
			reduce(25),		/* >, reduce: Factor */
			reduce(25),		/* >=, reduce: Factor */
			reduce(25),		/* <, reduce: Factor */
			reduce(25),		/* <=, reduce: Factor */
			reduce(25),		/* =, reduce: Factor */
			reduce(25),		/* ==, reduce: Factor */
			reduce(25),		/* !=, reduce: Factor */
			reduce(25),		/* is not, reduce: Factor */
			reduce(25),		/* is, reduce: Factor */
			reduce(25),		/* contains, reduce: Factor */
			reduce(25),		/* matches, reduce: Factor */
			shift(32),		/* int_lit */
			shift(33),		/* string_lit */
			shift(34),		/* float_lit */
			shift(35),		/* variable */
			shift(36),		/* true */
			shift(37),		/* false */
			shift(38),		/* undefined */
			shift(39),		/* null */
			nil,		/* empty */
			shift(40),		/* ( */
			reduce(25),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S53
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(6),		/* $, reduce: Term */
			reduce(6),		/* and, reduce: Term */
			reduce(6),		/* or, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S54
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(7),		/* $, reduce: Term */
			reduce(7),		/* and, reduce: Term */
			reduce(7),		/* or, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S55
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(8),		/* $, reduce: Term */
			reduce(8),		/* and, reduce: Term */
			reduce(8),		/* or, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S56
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(9),		/* $, reduce: Term */
			reduce(9),		/* and, reduce: Term */
			reduce(9),		/* or, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S57
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(10),		/* $, reduce: Term */
			reduce(10),		/* and, reduce: Term */
			reduce(10),		/* or, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S58
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(11),		/* $, reduce: Term */
			reduce(11),		/* and, reduce: Term */
			reduce(11),		/* or, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S59
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(12),		/* $, reduce: Term */
			reduce(12),		/* and, reduce: Term */
			reduce(12),		/* or, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S60
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(13),		/* $, reduce: Term */
			reduce(13),		/* and, reduce: Term */
			reduce(13),		/* or, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S61
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(14),		/* $, reduce: Term */
			reduce(14),		/* and, reduce: Term */
			reduce(14),		/* or, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S62
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(15),		/* $, reduce: Term */
			reduce(15),		/* and, reduce: Term */
			reduce(15),		/* or, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S63
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			shift(29),		/* not */
			reduce(25),		/* >, reduce: Factor */
			reduce(25),		/* >=, reduce: Factor */
			reduce(25),		/* <, reduce: Factor */
			reduce(25),		/* <=, reduce: Factor */
			reduce(25),		/* =, reduce: Factor */
			reduce(25),		/* ==, reduce: Factor */
			reduce(25),		/* !=, reduce: Factor */
			reduce(25),		/* is not, reduce: Factor */
			reduce(25),		/* is, reduce: Factor */
			reduce(25),		/* contains, reduce: Factor */
			reduce(25),		/* matches, reduce: Factor */
			shift(32),		/* int_lit */
			shift(33),		/* string_lit */
			shift(34),		/* float_lit */
			shift(35),		/* variable */
			shift(36),		/* true */
			shift(37),		/* false */
			shift(38),		/* undefined */
			shift(39),		/* null */
			nil,		/* empty */
			shift(40),		/* ( */
			reduce(25),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S64
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			shift(29),		/* not */
			reduce(25),		/* >, reduce: Factor */
			reduce(25),		/* >=, reduce: Factor */
			reduce(25),		/* <, reduce: Factor */
			reduce(25),		/* <=, reduce: Factor */
			reduce(25),		/* =, reduce: Factor */
			reduce(25),		/* ==, reduce: Factor */
			reduce(25),		/* !=, reduce: Factor */
			reduce(25),		/* is not, reduce: Factor */
			reduce(25),		/* is, reduce: Factor */
			reduce(25),		/* contains, reduce: Factor */
			reduce(25),		/* matches, reduce: Factor */
			shift(32),		/* int_lit */
			shift(33),		/* string_lit */
			shift(34),		/* float_lit */
			shift(35),		/* variable */
			shift(36),		/* true */
			shift(37),		/* false */
			shift(38),		/* undefined */
			shift(39),		/* null */
			nil,		/* empty */
			shift(40),		/* ( */
			reduce(25),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S65
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(26),		/* $, reduce: Factor */
			reduce(26),		/* and, reduce: Factor */
			reduce(26),		/* or, reduce: Factor */
			nil,		/* not */
			reduce(26),		/* >, reduce: Factor */
			reduce(26),		/* >=, reduce: Factor */
			reduce(26),		/* <, reduce: Factor */
			reduce(26),		/* <=, reduce: Factor */
			reduce(26),		/* =, reduce: Factor */
			reduce(26),		/* ==, reduce: Factor */
			reduce(26),		/* !=, reduce: Factor */
			reduce(26),		/* is not, reduce: Factor */
			reduce(26),		/* is, reduce: Factor */
			reduce(26),		/* contains, reduce: Factor */
			reduce(26),		/* matches, reduce: Factor */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S66
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			shift(63),		/* and */
			shift(64),		/* or */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(3),		/* ), reduce: Expression */
			
		},

	},
	actionRow{ // S67
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(83),		/* int_lit */
			shift(84),		/* string_lit */
			shift(85),		/* float_lit */
			shift(86),		/* variable */
			shift(87),		/* true */
			shift(88),		/* false */
			shift(89),		/* undefined */
			shift(90),		/* null */
			nil,		/* empty */
			shift(91),		/* ( */
			reduce(25),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S68
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(83),		/* int_lit */
			shift(84),		/* string_lit */
			shift(85),		/* float_lit */
			shift(86),		/* variable */
			shift(87),		/* true */
			shift(88),		/* false */
			shift(89),		/* undefined */
			shift(90),		/* null */
			nil,		/* empty */
			shift(91),		/* ( */
			reduce(25),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S69
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(83),		/* int_lit */
			shift(84),		/* string_lit */
			shift(85),		/* float_lit */
			shift(86),		/* variable */
			shift(87),		/* true */
			shift(88),		/* false */
			shift(89),		/* undefined */
			shift(90),		/* null */
			nil,		/* empty */
			shift(91),		/* ( */
			reduce(25),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S70
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(83),		/* int_lit */
			shift(84),		/* string_lit */
			shift(85),		/* float_lit */
			shift(86),		/* variable */
			shift(87),		/* true */
			shift(88),		/* false */
			shift(89),		/* undefined */
			shift(90),		/* null */
			nil,		/* empty */
			shift(91),		/* ( */
			reduce(25),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S71
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(83),		/* int_lit */
			shift(84),		/* string_lit */
			shift(85),		/* float_lit */
			shift(86),		/* variable */
			shift(87),		/* true */
			shift(88),		/* false */
			shift(89),		/* undefined */
			shift(90),		/* null */
			nil,		/* empty */
			shift(91),		/* ( */
			reduce(25),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S72
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(83),		/* int_lit */
			shift(84),		/* string_lit */
			shift(85),		/* float_lit */
			shift(86),		/* variable */
			shift(87),		/* true */
			shift(88),		/* false */
			shift(89),		/* undefined */
			shift(90),		/* null */
			nil,		/* empty */
			shift(91),		/* ( */
			reduce(25),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S73
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(83),		/* int_lit */
			shift(84),		/* string_lit */
			shift(85),		/* float_lit */
			shift(86),		/* variable */
			shift(87),		/* true */
			shift(88),		/* false */
			shift(89),		/* undefined */
			shift(90),		/* null */
			nil,		/* empty */
			shift(91),		/* ( */
			reduce(25),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S74
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(83),		/* int_lit */
			shift(84),		/* string_lit */
			shift(85),		/* float_lit */
			shift(86),		/* variable */
			shift(87),		/* true */
			shift(88),		/* false */
			shift(89),		/* undefined */
			shift(90),		/* null */
			nil,		/* empty */
			shift(91),		/* ( */
			reduce(25),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S75
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(83),		/* int_lit */
			shift(84),		/* string_lit */
			shift(85),		/* float_lit */
			shift(86),		/* variable */
			shift(87),		/* true */
			shift(88),		/* false */
			shift(89),		/* undefined */
			shift(90),		/* null */
			nil,		/* empty */
			shift(91),		/* ( */
			reduce(25),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S76
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(83),		/* int_lit */
			shift(84),		/* string_lit */
			shift(85),		/* float_lit */
			shift(86),		/* variable */
			shift(87),		/* true */
			shift(88),		/* false */
			shift(89),		/* undefined */
			shift(90),		/* null */
			nil,		/* empty */
			shift(91),		/* ( */
			reduce(25),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S77
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			shift(83),		/* int_lit */
			shift(84),		/* string_lit */
			shift(85),		/* float_lit */
			shift(86),		/* variable */
			shift(87),		/* true */
			shift(88),		/* false */
			shift(89),		/* undefined */
			shift(90),		/* null */
			nil,		/* empty */
			shift(91),		/* ( */
			reduce(25),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S78
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			shift(63),		/* and */
			shift(64),		/* or */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			shift(102),		/* ) */
			
		},

	},
	actionRow{ // S79
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			shift(63),		/* and */
			shift(64),		/* or */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			shift(103),		/* ) */
			
		},

	},
	actionRow{ // S80
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			shift(63),		/* and */
			shift(64),		/* or */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(1),		/* ), reduce: Expression */
			
		},

	},
	actionRow{ // S81
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			shift(63),		/* and */
			shift(64),		/* or */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(2),		/* ), reduce: Expression */
			
		},

	},
	actionRow{ // S82
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(5),		/* and, reduce: Term */
			reduce(5),		/* or, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(5),		/* ), reduce: Term */
			
		},

	},
	actionRow{ // S83
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(17),		/* and, reduce: Factor */
			reduce(17),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(17),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S84
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(18),		/* and, reduce: Factor */
			reduce(18),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(18),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S85
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(19),		/* and, reduce: Factor */
			reduce(19),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(19),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S86
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(20),		/* and, reduce: Factor */
			reduce(20),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(20),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S87
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(21),		/* and, reduce: Factor */
			reduce(21),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(21),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S88
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(22),		/* and, reduce: Factor */
			reduce(22),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(22),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S89
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(23),		/* and, reduce: Factor */
			reduce(23),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(23),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S90
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(24),		/* and, reduce: Factor */
			reduce(24),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(24),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S91
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(25),		/* and, reduce: Factor */
			reduce(25),		/* or, reduce: Factor */
			shift(29),		/* not */
			reduce(25),		/* >, reduce: Factor */
			reduce(25),		/* >=, reduce: Factor */
			reduce(25),		/* <, reduce: Factor */
			reduce(25),		/* <=, reduce: Factor */
			reduce(25),		/* =, reduce: Factor */
			reduce(25),		/* ==, reduce: Factor */
			reduce(25),		/* !=, reduce: Factor */
			reduce(25),		/* is not, reduce: Factor */
			reduce(25),		/* is, reduce: Factor */
			reduce(25),		/* contains, reduce: Factor */
			reduce(25),		/* matches, reduce: Factor */
			shift(32),		/* int_lit */
			shift(33),		/* string_lit */
			shift(34),		/* float_lit */
			shift(35),		/* variable */
			shift(36),		/* true */
			shift(37),		/* false */
			shift(38),		/* undefined */
			shift(39),		/* null */
			nil,		/* empty */
			shift(40),		/* ( */
			reduce(25),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S92
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(6),		/* and, reduce: Term */
			reduce(6),		/* or, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(6),		/* ), reduce: Term */
			
		},

	},
	actionRow{ // S93
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(7),		/* and, reduce: Term */
			reduce(7),		/* or, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(7),		/* ), reduce: Term */
			
		},

	},
	actionRow{ // S94
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(8),		/* and, reduce: Term */
			reduce(8),		/* or, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(8),		/* ), reduce: Term */
			
		},

	},
	actionRow{ // S95
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(9),		/* and, reduce: Term */
			reduce(9),		/* or, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(9),		/* ), reduce: Term */
			
		},

	},
	actionRow{ // S96
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(10),		/* and, reduce: Term */
			reduce(10),		/* or, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(10),		/* ), reduce: Term */
			
		},

	},
	actionRow{ // S97
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(11),		/* and, reduce: Term */
			reduce(11),		/* or, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(11),		/* ), reduce: Term */
			
		},

	},
	actionRow{ // S98
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(12),		/* and, reduce: Term */
			reduce(12),		/* or, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(12),		/* ), reduce: Term */
			
		},

	},
	actionRow{ // S99
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(13),		/* and, reduce: Term */
			reduce(13),		/* or, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(13),		/* ), reduce: Term */
			
		},

	},
	actionRow{ // S100
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(14),		/* and, reduce: Term */
			reduce(14),		/* or, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(14),		/* ), reduce: Term */
			
		},

	},
	actionRow{ // S101
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(15),		/* and, reduce: Term */
			reduce(15),		/* or, reduce: Term */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(15),		/* ), reduce: Term */
			
		},

	},
	actionRow{ // S102
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(26),		/* and, reduce: Factor */
			reduce(26),		/* or, reduce: Factor */
			nil,		/* not */
			reduce(26),		/* >, reduce: Factor */
			reduce(26),		/* >=, reduce: Factor */
			reduce(26),		/* <, reduce: Factor */
			reduce(26),		/* <=, reduce: Factor */
			reduce(26),		/* =, reduce: Factor */
			reduce(26),		/* ==, reduce: Factor */
			reduce(26),		/* !=, reduce: Factor */
			reduce(26),		/* is not, reduce: Factor */
			reduce(26),		/* is, reduce: Factor */
			reduce(26),		/* contains, reduce: Factor */
			reduce(26),		/* matches, reduce: Factor */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(26),		/* ), reduce: Factor */
			
		},

	},
	actionRow{ // S103
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			reduce(26),		/* $, reduce: Factor */
			reduce(26),		/* and, reduce: Factor */
			reduce(26),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			nil,		/* ) */
			
		},

	},
	actionRow{ // S104
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			shift(63),		/* and */
			shift(64),		/* or */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			shift(105),		/* ) */
			
		},

	},
	actionRow{ // S105
				canRecover: false,
		actions: [numSymbols]action{
			nil,		/* INVALID */
			nil,		/* $ */
			reduce(26),		/* and, reduce: Factor */
			reduce(26),		/* or, reduce: Factor */
			nil,		/* not */
			nil,		/* > */
			nil,		/* >= */
			nil,		/* < */
			nil,		/* <= */
			nil,		/* = */
			nil,		/* == */
			nil,		/* != */
			nil,		/* is not */
			nil,		/* is */
			nil,		/* contains */
			nil,		/* matches */
			nil,		/* int_lit */
			nil,		/* string_lit */
			nil,		/* float_lit */
			nil,		/* variable */
			nil,		/* true */
			nil,		/* false */
			nil,		/* undefined */
			nil,		/* null */
			nil,		/* empty */
			nil,		/* ( */
			reduce(26),		/* ), reduce: Factor */
			
		},

	},
	
}

