
// generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 4
type(
	gotoTable [numStates]gotoRow
	gotoRow	[numNTSymbols] int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		
		-1, // S'
		1, // Expression
		3, // Term
		4, // Factor
		

	},
	gotoRow{ // S1
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S2
		
		-1, // S'
		16, // Expression
		3, // Term
		4, // Factor
		

	},
	gotoRow{ // S3
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S4
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S5
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S6
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S7
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S8
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S9
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S10
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S11
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S12
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S13
		
		-1, // S'
		28, // Expression
		30, // Term
		31, // Factor
		

	},
	gotoRow{ // S14
		
		-1, // S'
		41, // Expression
		3, // Term
		4, // Factor
		

	},
	gotoRow{ // S15
		
		-1, // S'
		42, // Expression
		3, // Term
		4, // Factor
		

	},
	gotoRow{ // S16
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S17
		
		-1, // S'
		-1, // Expression
		-1, // Term
		43, // Factor
		

	},
	gotoRow{ // S18
		
		-1, // S'
		-1, // Expression
		-1, // Term
		53, // Factor
		

	},
	gotoRow{ // S19
		
		-1, // S'
		-1, // Expression
		-1, // Term
		54, // Factor
		

	},
	gotoRow{ // S20
		
		-1, // S'
		-1, // Expression
		-1, // Term
		55, // Factor
		

	},
	gotoRow{ // S21
		
		-1, // S'
		-1, // Expression
		-1, // Term
		56, // Factor
		

	},
	gotoRow{ // S22
		
		-1, // S'
		-1, // Expression
		-1, // Term
		57, // Factor
		

	},
	gotoRow{ // S23
		
		-1, // S'
		-1, // Expression
		-1, // Term
		58, // Factor
		

	},
	gotoRow{ // S24
		
		-1, // S'
		-1, // Expression
		-1, // Term
		59, // Factor
		

	},
	gotoRow{ // S25
		
		-1, // S'
		-1, // Expression
		-1, // Term
		60, // Factor
		

	},
	gotoRow{ // S26
		
		-1, // S'
		-1, // Expression
		-1, // Term
		61, // Factor
		

	},
	gotoRow{ // S27
		
		-1, // S'
		-1, // Expression
		-1, // Term
		62, // Factor
		

	},
	gotoRow{ // S28
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S29
		
		-1, // S'
		66, // Expression
		30, // Term
		31, // Factor
		

	},
	gotoRow{ // S30
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S31
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S32
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S33
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S34
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S35
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S36
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S37
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S38
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S39
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S40
		
		-1, // S'
		78, // Expression
		30, // Term
		31, // Factor
		

	},
	gotoRow{ // S41
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S42
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S43
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S44
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S45
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S46
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S47
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S48
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S49
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S50
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S51
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S52
		
		-1, // S'
		79, // Expression
		30, // Term
		31, // Factor
		

	},
	gotoRow{ // S53
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S54
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S55
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S56
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S57
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S58
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S59
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S60
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S61
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S62
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S63
		
		-1, // S'
		80, // Expression
		30, // Term
		31, // Factor
		

	},
	gotoRow{ // S64
		
		-1, // S'
		81, // Expression
		30, // Term
		31, // Factor
		

	},
	gotoRow{ // S65
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S66
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S67
		
		-1, // S'
		-1, // Expression
		-1, // Term
		82, // Factor
		

	},
	gotoRow{ // S68
		
		-1, // S'
		-1, // Expression
		-1, // Term
		92, // Factor
		

	},
	gotoRow{ // S69
		
		-1, // S'
		-1, // Expression
		-1, // Term
		93, // Factor
		

	},
	gotoRow{ // S70
		
		-1, // S'
		-1, // Expression
		-1, // Term
		94, // Factor
		

	},
	gotoRow{ // S71
		
		-1, // S'
		-1, // Expression
		-1, // Term
		95, // Factor
		

	},
	gotoRow{ // S72
		
		-1, // S'
		-1, // Expression
		-1, // Term
		96, // Factor
		

	},
	gotoRow{ // S73
		
		-1, // S'
		-1, // Expression
		-1, // Term
		97, // Factor
		

	},
	gotoRow{ // S74
		
		-1, // S'
		-1, // Expression
		-1, // Term
		98, // Factor
		

	},
	gotoRow{ // S75
		
		-1, // S'
		-1, // Expression
		-1, // Term
		99, // Factor
		

	},
	gotoRow{ // S76
		
		-1, // S'
		-1, // Expression
		-1, // Term
		100, // Factor
		

	},
	gotoRow{ // S77
		
		-1, // S'
		-1, // Expression
		-1, // Term
		101, // Factor
		

	},
	gotoRow{ // S78
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S79
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S80
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S81
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S82
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S83
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S84
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S85
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S86
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S87
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S88
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S89
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S90
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S91
		
		-1, // S'
		104, // Expression
		30, // Term
		31, // Factor
		

	},
	gotoRow{ // S92
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S93
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S94
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S95
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S96
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S97
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S98
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S99
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S100
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S101
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S102
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S103
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S104
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	gotoRow{ // S105
		
		-1, // S'
		-1, // Expression
		-1, // Term
		-1, // Factor
		

	},
	
}
